# Fix DevTools restart classloader conflict
restart.include.hibernate-core=/hibernate-core-.*\.jar
restart.include.hibernate-models=/hibernate-models-.*\.jar
restart.include.byte-buddy=/byte-buddy-.*\.jar
restart.include.classmate=/classmate-.*\.jar
restart.include.antlr=/antlr4-runtime-.*\.jar
restart.include.jakarta-persistence=/jakarta.persistence-api-.*\.jar
restart.include.jakarta-transaction=/jakarta.transaction-api-.*\.jar
restart.include.jboss-logging=/jboss-logging-.*\.jar
